### ISSUE TITLE
server: Log requests and user agents and return 200 to user agents that should not render the registry html

### ISSUE THREAD

**Issue by fntlnz** [seqeralabs/staticreg#13]
In some cases is desirable  to avoid rendering the html page or miss a cache when the request comes from a certain user agent.

We can implement this by allowing the user to pass a list of ignored user agents when starting `staticreg server`.

To make it easier, we can also log user agents when staticreg is started with a debug loglevel.

**Comment by fntlnz** [comment]
@pditommaso we got a PR in review for this, please take a look!

**Comment by pditommaso** [comment]
Cool! I leave the review to somebody else in the team
