### ISSUE TITLE
Reduce refresh pull rate 

### ISSUE THREAD

**Issue by pditommaso** [seqeralabs/staticreg#20]
The registry pulling rate when refreshing staticreg content should be reduced to prevent polluting access metrics. 

Slack convo [here](https://seqera.slack.com/archives/C03117E4RAB/p1729516465386479).

**Comment by pditommaso** [comment]
Will a patch release made available?

**Comment by fntlnz** [comment]
Included in the 0.3.0 release https://github.com/seqeralabs/staticreg/releases/tag/0.3.0
